M48
; DRILL file {KiCad 9.0.7} date 2026-05-31T22:44:31-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-31T22:44:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.300
%
G90
G05
T1
X54.275Y51.9
X60.055Y51.9
X72.31Y51.945
X78.09Y51.945
T2
X45.526Y10.105
M30
